name: Deploy to TechCore
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          description: Latest release of the TechCore Github Action
